I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 264, in script
    python:
ScriptError: could not find label 'start'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\Game\Desktop\renpy-7.1.1-sdk\renpy\bootstrap.py", line 313, in bootstrap
    renpy.main.main()
  File "C:\Users\Game\Desktop\renpy-7.1.1-sdk\renpy\main.py", line 513, in main
    run(restart)
  File "C:\Users\Game\Desktop\renpy-7.1.1-sdk\renpy\main.py", line 139, in run
    renpy.execution.run_context(True)
  File "C:\Users\Game\Desktop\renpy-7.1.1-sdk\renpy\execution.py", line 876, in run_context
    context.run()
  File "renpy/common/00start.rpy", line 264, in script
    python:
  File "C:\Users\Game\Desktop\renpy-7.1.1-sdk\renpy\script.py", line 875, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'start'.

Windows-8-6.2.9200
Ren'Py 7.1.1.929
Valkyries Descending 1.0
Tue Dec 11 09:42:02 2018
